In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("ITIL.csv")

In [4]:
df.head(10000)

,Issue ID,Issue Title,Issue Category,Infra Category,SAP Category,SP Category,Sub-category,Site Type,Issue Status,Requested By,...,flagAutoClose,Staff Responsiveness,Performance and Competency,Overall Support Quality Satisfaction,Average CS,flagResponseCompleted,Turnaround RD,Turnaround CD,SLA Hours,Turnaround RD Hours
0,ITIL-12883-20,Wifi Access,IT Infra,Network,NaN,NaN,Network,IT Infra - TGBIN,Closed,Mohd Firdaus Radzuan - MPB;#2194,...,True,NaN,NaN,NaN,NaN,False,16:09:00,NaN,24:00:00,16.15
1,ITIL-12881-20,Setup VPN,IT Infra,Network,NaN,NaN,Network,IT Infra - TGBIN,Closed,Osman Ahmad - MPB;#1808,...,False,5.0,5.0,5.0,5.0,True,0:04:00,NaN,24:00:00,0.08
2,ITIL-12880-20,Ghost Mouse Request,IT Infra,Software,NaN,NaN,Software,IT Infra - TGBIN,Closed,Hairul Anuar Ngadi - MPB;#1514,...,True,NaN,NaN,NaN,NaN,False,2:37:00,NaN,48:00:00,2.62
3,ITIL-12879-20,Install SVG,IT Infra,Software,NaN,NaN,Software,IT Infra - TGBIN,Closed,Muhammad Rohaizad Hussin - MPB;#230,...,True,NaN,NaN,NaN,NaN,False,46:27:00,NaN,24:00:00,46.47
4,ITIL-12877-20,PTW NISOFT,IT Infra,Software,NaN,NaN,Software,IT Infra - TGBIN,Closed,Mohammad Asyraf Abd Rashid - MPB;#1361,...,True,NaN,NaN,NaN,NaN,False,0:16:00,NaN,4:00,0.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8799,ITIL-15464-21,Meeting Room Online Booking not seen in Macnet...,SharePoint,NaN,NaN,MaCNet,MaCNet,SP Team,Resolved,Mohd Shahril Ridzuan Mohd Nor - MPB;#508,...,False,NaN,NaN,NaN,NaN,False,0,-,24:00:00,0.12
8800,ITIL-15465-21,ID locked,SAP,NaN,Reset Password,NaN,Reset Password SAP,SAP Team,Closed,Nur Adyani Abdul Latiff - MCB;#15,...,False,5.0,5.0,5.0,5.0,True,0,-,24:00:00,0.07
8801,ITIL-15466-21,To correct Agreement List Plant&Company Code,SAP,NaN,VDMP,NaN,VDMP,SAP Team,Open,Nurisma Md Omar - MCB;#619,...,False,NaN,NaN,NaN,NaN,False,-,-,4:00,
8802,ITIL-15467-21,Parent Account Cannot Be Billed - 3000057 & 30...,SAP,NaN,CBIS,NaN,CBIS,SAP Team,Open,Fikriyah Mohd Mukhtar - MUSB;#1526,...,False,NaN,NaN,NaN,NaN,False,-,-,4:00,
8803,ITIL-15468-21,Installation Adobe Acrobat Pro DC,IT Infra,New Request,NaN,NaN,New Request,IT Infra - HQ,Open,Muhammad Ruziani Abdul Razak - MUSB;#811,...,False,NaN,NaN,NaN,NaN,False,-,-,24:00:00,

In [6]:
df_2 = pd.DataFrame(df["Issue Status"], columns=['A', 'Open Tickets'])

In [7]:
df_2.head()

Empty DataFrame
Columns: [A, Open Tickets]
Index: []

In [8]:
df_2["A"] = df["Issue Status"]

In [9]:
df_2.head()

        A Open Tickets
0  Closed          NaN
1  Closed          NaN
2  Closed          NaN
3  Closed          NaN
4  Closed          NaN

In [10]:
df_2["Open Tickets"][df_2['A'].str.contains("Open", na=False)] = '1'

In [11]:
df_2["Open Tickets"] = df_2["Open Tickets"].fillna(0)

In [13]:
df_2.head(30000)

             A Open Tickets
0       Closed            0
1       Closed            0
2       Closed            0
3       Closed            0
4       Closed            0
...        ...          ...
8799  Resolved            0
8800    Closed            0
8801      Open            1
8802      Open            1
8803      Open            1

[8804 rows x 2 columns]

In [15]:
df_2 = df_2.drop(columns=['A'])

In [16]:
df_final = pd.concat([df, df_2], axis=1)

In [17]:
df_final.head()

,Issue ID,Issue Title,Issue Category,Infra Category,SAP Category,SP Category,Sub-category,Site Type,Issue Status,Requested By,...,Staff Responsiveness,Performance and Competency,Overall Support Quality Satisfaction,Average CS,flagResponseCompleted,Turnaround RD,Turnaround CD,SLA Hours,Turnaround RD Hours,Open Tickets
0,ITIL-12883-20,Wifi Access,IT Infra,Network,NaN,NaN,Network,IT Infra - TGBIN,Closed,Mohd Firdaus Radzuan - MPB;#2194,...,NaN,NaN,NaN,NaN,False,16:09:00,NaN,24:00:00,16.15,0
1,ITIL-12881-20,Setup VPN,IT Infra,Network,NaN,NaN,Network,IT Infra - TGBIN,Closed,Osman Ahmad - MPB;#1808,...,5.0,5.0,5.0,5.0,True,0:04:00,NaN,24:00:00,0.08,0
2,ITIL-12880-20,Ghost Mouse Request,IT Infra,Software,NaN,NaN,Software,IT Infra - TGBIN,Closed,Hairul Anuar Ngadi - MPB;#1514,...,NaN,NaN,NaN,NaN,False,2:37:00,NaN,48:00:00,2.62,0
3,ITIL-12879-20,Install SVG,IT Infra,Software,NaN,NaN,Software,IT Infra - TGBIN,Closed,Muhammad Rohaizad Hussin - MPB;#230,...,NaN,NaN,NaN,NaN,False,46:27:00,NaN,24:00:00,46.47,0
4,ITIL-12877-20,PTW NISOFT,IT Infra,Software,NaN,NaN,Software,IT Infra - TGBIN,Closed,Mohammad Asyraf Abd Rashid - MPB;#1361,...,NaN,NaN,NaN,NaN,False,0:16:00,NaN,4:00,0.28,0

In [18]:
df_final.to_csv('ITIL.csv', index = False, header=True)